library(lmtest)
library(snpar)
library(car)
library(stats)
olah = read.csv("C:/Users/Siti Annisa/Downloads/OlahDataPKL/KecamatanBrebesOnly.csv")
model = lm(JumlahProduksi ~ LuasPanen + CurahHujan + HariHujan + JumlahPekerja, data = olah)
residual = resid(model)
plot(model)
shapiro.test(residual)
bptest(model, studentize = F, data=olah)
dwtest(model)
runs.test(residual)
vif(model)
summary(model)